### PR TITLE
shell: Added fish completions using Cobra

### PR DESCRIPTION
**Pull request by StealthyCoder**
Just using the standard function exposed by Cobra to generate Fish
completions. Had to update the dependency of cobra to latest version
though.

### CODE REVIEW

**Comment by doanac** [comment]
should be a simple change, but this is a huge update to cobra. we should poke around and make sure nothing has broken

**Comment by doanac** [comment]
beyond some smoke testing of the commands, we should look compare before/after changes to `fioctl gen-rst` to make sure its still going to produce valid content for docs.foundries.io.

**Comment by StealthyCoder** [comment]
I just generated the docs with `fioctl gen-rst` in a directory `new_docs` with the build from this branch. I generated docs with `fioctl gen-rst` into `old-docs` with the release v0.23. 

I then did a diff between all files and the only difference is the following:

```
fioctl_completion.rst
46,48d45
<   # Fish:
<   $ fioctl completion fish > ~/.config/fish/completions/fioctl.fish
< 
``` 

Which makes sense as that is the one thing I added in this commit. Is that enough of a check to make it all good?

**Comment by doanac** [comment]
can you added [signed-off-by](https://gerrit-review.googlesource.com/Documentation/user-signedoffby.html) i.e. `git commit --sigoff ...`

**Comment by StealthyCoder** [comment]
Added the Signed-off-by and Reviewed-by :+1:

**Review by doanac — APPROVED** [review]

**Pull request merged**
