### PR TITLE
Add a command for showing CI artifacts 

### PR DESCRIPTION
**Pull request by doanac**

### CODE REVIEW

**Comment by doanac** [comment]
@MatthewCroughan @vkhoroz - this is pretty rudimentary but I think it does what you two were discussing.

**Comment by MatthewCroughan** [comment]
Is it possible we could implement globbing? For example, if I want to download all the artifacts from `raspberrypi4-64` I'd execute:

`fioctl targets artifacts 18 raspberrypi4-64/*`

```
matthew@thinkpad ~/git/fioctl/bin (artifacts) $ ./fioctl-linux-amd64 targets artifacts 18 -f cowboy
raspberrypi4-64 https://api.foundries.io/projects/cowboy/lmp/builds/18/runs/raspberrypi4-64/
raspberrypi4-64/console.log
raspberrypi4-64/customize-target.log
raspberrypi4-64/lmp-factory-image-raspberrypi4-64.wic.gz
raspberrypi4-64/other/MD5SUMS.txt
raspberrypi4-64/other/at86rf233-raspberrypi4-64.dtbo
raspberrypi4-64/other/at86rf233.dtbo
raspberrypi4-64/other/bcm2711-rpi-4-b-raspberrypi4-64.dtb
raspberrypi4-64/other/bcm2711-rpi-4-b.dtb
raspberrypi4-64/other/bootfiles/bootcode.bin
```

**Comment by MatthewCroughan** [comment]
I did not realise it just puts this stuff to stdout. Instead of:
```
  # Download an artifact
  fioctl targets artifacts 12 publish-compose-apps/console.log
```

Maybe the example should be:

```
  # Download artifact contents to stdout.
  fioctl targets artifacts 12 publish-compose-apps/console.log
```

**Comment by doanac** [comment]
> Maybe the example should be:

@MatthewCroughan - good catch. that's actually copy/paste from the usage of the `fioctl targets test` command. I'll clean that up.

> Is it possible we could implement globbing? 

That sort of turns this into a download manager. That would be cool, but is probably beyond our scope right now

**Pull request merged**
