### PR TITLE
Add support for new users API

### PR DESCRIPTION
**Pull request by doanac**
The OTA Lite API now includes some user lookup information that's handy for this command.

### CODE REVIEW

**Comment by doanac** [comment]
let me rebase this.

**Comment by doanac** [comment]
@mike-scott - this is rebased and "working for me" now.

**Comment by mike-scott** [comment]
I re-tested this w/ 4dbd1f26c16416a6a9a8fccd88ac15dad17caac1 cherry-picked on top and it looks really nice.

**Comment by doanac** [comment]
I've rebased the changes to work with the new/improved CLI arg handling.

**Pull request merged**
