### PR TITLE
Include aktualizr config in device-show

### PR DESCRIPTION
**Pull request by doanac**
The ota-lite API now includes this optional data.

Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
@mike-sul - this is the corresponding change to the ota-lite API change I pushed for review. It produces output like:
~~~
$ ./data/fioctl.sh devices show device-on-prem
UUID:		08ebdc84-84cb-4b6b-a937-2740c3c874b5
Owner:		admin
Factory:	default
Up to date:	false
Target:		 / sha256()
Ostree Hash:	
Created:	2020-07-13T15:24:12+00:00
Last Seen:	
Aktulizr-lite configuration:
	| FOO\nbar

-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7+zShdJ7YBfnr6TdpAH9rIopt3EN
ZagQH889RfasveU3FIukBln+/2nm7ocqBkq8o80CtkfJ4U9QJysJ6VmtWQ==
-----END PUBLIC KEY-----
~~~

**Review by mike-sul — APPROVED** [review]

**Review by mike-sul — APPROVED** [review]

**Comment by doanac** [comment]
I wonder if we really need to show this much information. Or we need some kind of "verbose" type flag? For a real device it looks like:
~~~
$ fioctl devices show andy-test
UUID:		dae07eb1-2553-433a-9839-16d6dd5f5cd4
Owner:		59db9c9a1c85010019e023cc
Factory:	andy-corp
Up to date:	true
Target:		raspberrypi3-64-lmp-137 / sha256(8c13b86eaeab65c28117c533f941bfdf4c5e3f72569feac3945a0a5a53409e2b)
Ostree Hash:	8c13b86eaeab65c28117c533f941bfdf4c5e3f72569feac3945a0a5a53409e2b
Created:	2020-07-31T16:32:38+00:00
Last Seen:	2020-09-09T21:10:22+00:00
Tags:		master
Docker Apps:	fiotest
Hardware Info:
	{
	  "capabilities": {
	    "cp15_barrier": true,
	    "setend": true,
	    "smp": "Symmetric Multi-Processing",
	    "swp": true
	  },
	  "claimed": true,
	  "class": "system",
	  "description": "Computer",
	  "id": "raspberrypi3-64-1",
	  "product": "Raspberry Pi 3 Model B",
	  "serial": "00000000132060de",
	  "width": 64
	}
Aktulizr-lite configuration:
	| [logger]
	| loglevel = 1
	| 
	| [p11]
	| module = "/usr/lib/softhsm/libsofthsm2.so"
	| pass = "87654321"
	| uptane_key_id = ""
	| tls_ca_id = ""
	| tls_pkey_id = "01"
	| tls_clientcert_id = "03"
	| 
	| [tls]
	| server = "https://ota-lite.foundries.io:8443"
	| server_url_path = ""
	| ca_source = "file"
	| pkey_source = "pkcs11"
	| cert_source = "pkcs11"
	| 
	| [provision]
	| server = "https://ota-lite.foundries.io:8443"
	| p12_password = ""
	| expiry_days = "36000"
	| provision_path = ""
	| device_id = ""
	| primary_ecu_serial = ""
	| primary_ecu_hardware_id = "raspberrypi3-64"
	| ecu_registration_endpoint = "https://ota-lite.foundries.io:8443/director/ecus"
	| 
	| [uptane]
	| polling_sec = 300
	| director_server = "https://ota-lite.foundries.io:8443/director"
	| repo_server = "https://ota-lite.foundries.io:8443/repo"
	| key_source = "file"
	| key_type = "RSA2048"
	| force_install_completion = false
	| secondary_config_file = ""
	| secondary_preinstall_wait_sec = 600
	| 
	| [pacman]
	| type = "ostree+compose_apps"
	| os = ""
	| sysroot = ""
	| ostree_server = "https://ota-lite.foundries.io:8443/treehub"
	| packages_file = "/usr/package.manifest"
	| fake_need_reboot = false
	| /var/sota/aklite-callback.sh = "callback_program"
	| fiotest = "compose_apps"
	| /var/sota/compose = "compose_apps_root"
	| fiotest = "docker_apps"
	| /var/sota/docker-apps = "docker_apps_root"
	| master = "tags"
	| 
	| [storage]
	| type = "sqlite"
	| path = "/var/sota/"
	| sqldb_path = "sql.db"
	| uptane_metadata_path = "/var/sota/metadata"
	| uptane_private_key_path = "ecukey.der"
	| uptane_public_key_path = "ecukey.pub"
	| tls_cacert_path = "root.crt"
	| tls_pkey_path = "pkey.pem"
	| tls_clientcert_path = "client.pem"
	| 
	| [import]
	| base_path = "/var/sota/import"
	| uptane_private_key_path = ""
	| uptane_public_key_path = ""
	| tls_cacert_path = "/var/sota/root.crt"
	| tls_pkey_path = ""
	| tls_clientcert_path = ""
	| 
	| [telemetry]
	| report_network = true
	| report_config = true
	| 
	| [bootloader]
	| rollback_mode = "uboot_masked"
	| reboot_sentinel_dir = "/var/run/aktualizr-session"
	| reboot_sentinel_name = "need_reboot"
	| reboot_command = "/sbin/reboot"
	| 
	| 

-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDJ4hCRz1hbCrhDNqGmFtgyiKcqrs
Pk0lVxcct9RxONwiUqCRSr5UaTvde92JN/vrT5QEkFNQUtUJzAfHstLQqw==
-----END PUBLIC KEY-----

~~~

**Comment by doanac** [comment]
@mike-scott - you have any thoughts/opinions?

**Comment by mike-sul** [comment]
> we need some kind of "verbose" type flag? 

+ for the "verbose" flag

**Pull request closed without merging**
