### PR TITLE
Add a new factory status command

### PR DESCRIPTION
**Pull request by doanac**
Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
I've re-worked this command to use the REST API we've worked out so that's more efficient and can be used by the webui as well. This now produces:
~~~
$ fioctl status
Total number of devices: 3

TAG       DEVICES  ON LATEST  ONLINE
---       -------  ---------  ------
master    2        0          0
promoted  1        1          1

## Tag: master
	TARGET  DEVICES  DETAILS
	------  -------  -------
	62      1        `fioctl targets show 62`
	12      1        `fioctl targets show 12`

## Tag: promoted
	TARGET  DEVICES  DETAILS
	------  -------  -------
	59      1        `fioctl targets show 59`
~~~

**Comment by doanac** [comment]
@MiloCasagrande - this might be of interest to you as well.

**Comment by mike-scott** [comment]
This looks great!

My only 2 comments:
1. Sort order for `TARGET  DEVICES  DETAILS` columns would be numeric sort for `TARGET` column in descending order (looks like it's semi-random atm)
2. We should probably add 1 more group for devices where a tag cannot be determined or is not assigned.  This would be older devices where we didn't automatically assign one during `lmp-device-register` and/or devices that were registered but never checked into the server to confirm hw/target data.

If #2 is too hard for this PR, we could get this in and add that later as this is already useful.

**Comment by mike-scott** [comment]
One idea for the next round of changes would be to have a flag which would include the devices under each target in the tag list.  Below is a terrible example of what I'm thinking of (formatting would need to be improved):

```
$fioctl status -f hashcode
Total number of devices: 6

TAG    DEVICES  ON LATEST  ONLINE
---    -------  ---------  ------
devel  6        6          0

## Tag: devel
	TARGET  DEVICES  DETAILS
	------  -------  -------
	90      1        `fioctl targets show 90`

	hashcode-hummingboard2-01	hashcode  Michael Scott  cubox-i-lmp-90
	hashcode-hummingboard2-02	hashcode  Michael Scott  cubox-i-lmp-90

	93      1        `fioctl targets show 93`

	mike-imx6ullevk-01		hashcode  Michael Scott  imx6ullevk-lmp-93
	mike-imx6ullevk-02		hashcode  Michael Scott  imx6ullevk-lmp-93

	96      1        `fioctl targets show 96`

	hashcode-intel-corei7-64-01	hashcode  Michael Scott  intel-corei7-64-lmp-96
	hashcode-intel-corei7-64-02	hashcode  Michael Scott  intel-corei7-64-lmp-96
```

**Comment by doanac** [comment]
> Sort order for TARGET DEVICES DETAILS columns could be a numeric sort for TARGET column in descending order (looks like it's semi-random atm)

I forgot - I intentionally made this an array so that I could handle things like that from the API. Its fixed on the backend now.

**Comment by doanac** [comment]
@mike-scott - the api and fioctl can now handle devices with out tags. I've also changed things to show the most recent target for a tag:
~~~
TAG       LATEST TARGET  DEVICES  ON LATEST  ONLINE
---       -------------  -------  ---------  ------
master    63             2        0          0
promoted  59             1        1          1
~~~

If a devices w/o tags show up under:
~~~
## Tag:(Untagged)
~~~

**Comment by mike-scott** [comment]
@doanac checking this again now

**Pull request merged**
