### PR TITLE
Add a wave status command

### PR DESCRIPTION
**Pull request by vkhoroz**
Signed-off-by: Volodymyr Khoroz <volodymyr.khoroz@foundries.io>

### CODE REVIEW

**Comment by vkhoroz** [comment]
Example Output:
```
Wave 'beta683new' for tag 'beta' version 683 is active

Created At: 	2021-03-18T20:59:17.856817
Number of Device Groups: 	2
Number of Devices: 		3
Number of Devices to Update: 	2

GROUP  TOTAL  IN WAVE  UP TO DATE  NEED UPDATE  NEWER VERSION  ONLINE  ROLLOUT AT
-----  -----  -------  ----------  -----------  -------------  ------  ----------
test   2      2        0           2            0              1       2021-03-18T20:59:24.456702
new    3      1        1           0            0              0       2021-03-19T15:34:38.179387

Orphan target versions below are marked with a star (*)
Wave target version below is marked with an arrow (<-)

## Device Group: test
	TARGET    DEVICES  INSTALLING  DETAILS
	--------  -------  ----------  -------
	617       1        0           `fioctl targets show 617`
	0      *  1        1           

## Device Group: new
	TARGET    DEVICES  INSTALLING  DETAILS
	--------  -------  ----------  -------
	683   <-  1        0           `fioctl targets show 683`
```

**Comment by doanac** [comment]
I'm going to do something unusual and review the output you shared *before* I read the code:
~~~
Wave 'beta683new' for tag 'beta' version 683 is active

Created At: 	2021-03-18T20:59:17.856817
Number of Device Groups: 	2
Number of Devices: 		3
// Is this total number of devices in groups or total number of devices on this Tag? Both are important - Total on the tag seems more important.
Number of Devices to Update: 	2

GROUP  TOTAL  IN WAVE  UP TO DATE  NEED UPDATE  NEWER VERSION  ONLINE  ROLLOUT AT
-----  -----  -------  ----------  -----------  -------------  ------  ----------
test   2      2        0           2            0              1       2021-03-18T20:59:24.456702
new    3      1        1           0            0              0       2021-03-19T15:34:38.179387
~~~
I'm not sure I understand what "in wave" means? I'd assume *all* devices in the group are in the wave? 

~~~
## Device Group: new
	TARGET    DEVICES  INSTALLING  DETAILS
	--------  -------  ----------  -------
	683   <-  1        0           `fioctl targets show 683`
~~~
I started to think "in wave" meant "updating" but the number don't seem to add up? whats the story of the other 2 devices in this group?
~~~

**Comment by doanac** [comment]
code seems fine - my questions are more about the usability and clarity of the output.

**Comment by vkhoroz** [comment]
> I'm going to do something unusual and review the output you shared _before_ I read the code:
> I'm not sure I understand what "in wave" means? I'd assume _all_ devices in the group are in the wave?
> I started to think "in wave" meant "updating" but the number don't seem to add up? whats the story of the other 2 devices in this group?

"In Wave" means those devices that participate in a wave i.e. should get updates associated with this wave.
A reason why `group-xyz-devices-total != group-xyz-devices-in-wave` is simple: a wave is associated with a tag, and not all devices in group xyz might have the same tag.

If all devices in group have the same tag and it equals a wave tag - then these two numbers are the same, like e.g. in a group test in my example output.

Initially I planned to name those columns as `GROUP TOTAL` and `WAVE TOTAL`, just deviced to use shorter names, cause to me it seemed trivial.  Maybe a name like `ON WAVE TAG` instead of `IN WAVE` or `WAVE TOTAL` would look even more clear.  Any thoughts ?

**Comment by doanac** [comment]
I think "in wave" makes sense. It really doesn't matter the label. People will find them confusing. I think we we need to is take your explanation and make that part of the usage text for this command.

**Comment by vkhoroz** [comment]
> I think we we need to is take your explanation and make that part of the usage text for this command.
Great idea... anything with more than 4 columns needs a good help message.

**Comment by vkhoroz** [comment]
An updated example per recent changes:
```
Wave 'beta683new' for tag 'beta' version 683 is active

Created At: 	2021-03-18T20:59:17.856817
Device Groups on Tag 'beta':   2
Device Groups Rollout:         2
Devices on Tag 'beta':         3
Devices Updated:               1
Devices Scheduled for Update:  2
Devices Not Scheduled:         0
GROUP  TOTAL  UP TO DATE  NEED UPDATE  NEWER VERSION  ONLINE  ROLLOUT AT
-----  -----  ----------  -----------  -------------  ------  ----------
test   2      0           2            0              0       2021-03-18T20:59:24.456702
new    1      1           0            0              0       2021-03-19T15:34:38.179387

Orphan target versions below are marked with a star (*)
Wave target version below is marked with an arrow (<-)

## Device Group: test
	TARGET    DEVICES  INSTALLING  DETAILS
	--------  -------  ----------  -------
	617       1        0           `fioctl targets show 617`
	0      *  1        1           

## Device Group: new
	TARGET    DEVICES  INSTALLING  DETAILS
	--------  -------  ----------  -------
	683   <-  1        0           `fioctl targets show 683`
```

Also an example for a canceled wave:
```
Wave 'beta683' for tag 'beta' version 683 is canceled

A device information is shown for a current time, not for a time when a wave was finished

Created At: 	2021-03-10T22:06:32.413689
Finished At: 	2021-03-18T20:59:03.776031
Device Groups on Tag 'beta':   2
Device Groups Rollout:         1
Devices on Tag 'beta':         3
Devices Updated:               1
Devices Scheduled for Update:  0
Devices Not Scheduled:         2
GROUP  TOTAL  UP TO DATE  NEED UPDATE  NEWER VERSION  ONLINE  ROLLOUT AT
-----  -----  ----------  -----------  -------------  ------  ----------
test   2      0           2            0              0       2021-03-10T22:06:45.884017
new    1      1           0            0              0       Never (Wave Canceled)
```

**Comment by vkhoroz** [comment]
@doanac I revised this command per your suggestion, but also added information about other devices in a factory that match a wave's tag (not only those in rollout groups).
That should help an operator to plan a wave properly e.g. then can run `wave status` right after creating a new wave to inspect which device groups have devices matching a wave tag (or even ungrouped devices) and plan a subsequent rollout plan accordingly.

**Comment by vkhoroz** [comment]
@doanac a question I have is this:
Does it make sense to merge "UP TO DATE" and "NEWER VERSION" columns into a single "UPDATED" column ?
Under normal circumstances "NEWER VERSION" should always be zero, I only included it to track an error use case when some devices are already at a newer version than a wave version, and apparently cannot downgrade to a wave version.

**Comment by doanac** [comment]
> Does it make sense to merge "UP TO DATE" and "NEWER VERSION" columns into a single "UPDATED" column ?

Maybe combine the columns in fioctl, but report both values via the API? then we'll have flexibility.

**Comment by doanac** [comment]
I think the code looks clean. I'm +1 once you are happy with the columns.

**Pull request merged**
