### PR TITLE
(chore): Update go version from 1.19 to 1.21 and dockerfile

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

Update go version 

## Motivation 

Solve tech-debt 

## Tested locally
- Golang build and docker file build

```
 $ docker build -t fioctl-build -f Dockerfile.build .
[+] Building 32.2s (11/11) FINISHED                        docker:desktop-linux
 => [internal] load build definition from Dockerfile.build                 0.0s
 => => transferring dockerfile: 286B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/golang:1.21.0-alpine3.  1.4s
 => [1/6] FROM docker.io/library/golang:1.21.0-alpine3.17@sha256:6467daf2  9.4s
 => => resolve docker.io/library/golang:1.21.0-alpine3.17@sha256:6467daf2  0.0s
 => => sha256:c93db5753d0c7e0b9c085935ddf1a54b1eb7fed49e5 6.18kB / 6.18kB  0.0s
 => => sha256:4060ece20d7ac783f52cbe28a35fd5b06f90f7b4d77 3.26MB / 3.26MB  0.5s
 => => sha256:adc7bbb5e99e84ba3fb2d95350e1269e7108ea7 286.37kB / 286.37kB  0.6s
 => => sha256:0eb1d125c0fbb027db413b8fd27d4e61831659067 63.99MB / 63.99MB  6.3s
 => => sha256:6467daf26aec6b82c750be4ca9b6aaf3a6a07ed22e1 1.65kB / 1.65kB  0.0s
 => => sha256:5bde5f87271115d9733fe5dc880e31bb06a2eef3f6c 1.16kB / 1.16kB  0.0s
 => => extracting sha256:4060ece20d7ac783f52cbe28a35fd5b06f90f7b4d773bae0  0.1s
 => => sha256:93714695fae3c6cad45f0f5df38c492033ce54d2a12c4f8 155B / 155B  1.0s
 => => extracting sha256:adc7bbb5e99e84ba3fb2d95350e1269e7108ea7e7ea4a8c4  0.0s
 => => extracting sha256:0eb1d125c0fbb027db413b8fd27d4e618316590679d4a3e7  2.9s
 => => extracting sha256:93714695fae3c6cad45f0f5df38c492033ce54d2a12c4f8a  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 23.16kB                                       0.0s
 => [2/6] RUN apk add --update --no-cache     git     g++     make         7.6s
 => [3/6] RUN mkdir -p $HOME/fioctl                                        0.1s
 => [4/6] WORKDIR /fioctl                                                  0.0s 
 => [5/6] COPY . .                                                         0.1s
 => [6/6] RUN go mod download                                             12.4s
 => exporting to image                                                     1.1s
 => => exporting layers                                                    1.1s
 => => writing image sha256:c1ed9a3e936a89ca3676486e0fbbe7d6f1c954c90e4b5  0.0s
 => => naming to docker.io/library/fioctl-build                            0.0s
```

### CODE REVIEW

**Review by doanac — COMMENTED** [review]
Looks good as long as it doesn't impact the crazy xgo stuff volodya is working through.

**Comment by camilamacedo86** [comment]
HI @doanac 

Thank you for the input 🎉 

Would this coverage https://github.com/foundriesio/fioctl/pull/275/files help us ensure that things do not break with bumps? Would also it help to validate the @vkhoroz xgo stuff?

**Comment by vkhoroz** [comment]
@camilamacedo86 I'd say we are not yet ready for this.

Our other projects (like e.g. `fioconfig`) are tied to Golang 1.19 at the moment.
Having different projects at different versions makes sense sometimes, but there should be a strong motivation for doing that.

On practice, Golang upgrades are not always smooth, sometimes they lead to subtle bugs, which are not always visible.
So, at the least this requires a thorough testing; not sure if we have the resource for that.

For the minimum, I already see [this code friction](https://github.com/foundriesio/fioctl/pull/272/files#r1335793568) related to the linter upgrade, which could be avoided.

So, in dry total:
- This is not a Chore, the Golang upgrade requires full regression testing.
- I doubt we have necessary resources for that, it causes a code friction, and there is no strong need for this change.

Thus, I recommend to reject this PR as not timely.

**Comment by camilamacedo86** [comment]
Hi @vkhoroz,

Thank you for sharing your insights; I value your perspective. Here are my thoughts on the points raised:

> Our other projects (like e.g. fioconfig) are tied to Golang 1.19 at the moment. 
> Having different projects at different versions makes sense sometimes, but there should be a strong motivation for doing that.

Considering Golang’s notable stability, is there a reason not to keep all projects updated? The introduction of tools like [Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) has considerably eased the process of managing updates and addressing CVEs, assuming there is basic coverage in place.

> On practice, Golang upgrades are not always smooth, sometimes they lead to subtle bugs, which are not always visible on surface.

Could you possibly share an example of this? I haven’t yet come across an instance where Golang’s stability led to a breaking change that wasn’t caught during the build. Any illustration of a scenario where a change in Golang might cause malfunction while still building successfully would be enlightening.

> For the minimum, I already see [this code friction](https://github.com/foundriesio/fioctl/pull/272/files#r1335793568) related to the linter upgrade, which could be avoided.

I see things a bit differently on this point. The referenced PR proposes adding a check to highlight deprecations, which we are currently overlooking. Addressing deprecations promptly is pivotal for maintaining a project effectively. The eventual need to replace deprecated methods is unavoidable, and early awareness allows for smoother transitions, preventing the myriad of issues that can stem from delayed updates.

> This is not a Chore, the Golang upgrade requires full regression testing.

**I’m curious to understand in which scenarios a Golang upgrade would introduce issues not identified during the build. Could you provide an example or elaborate a bit more on this?**

Thank you for considering my queries; I look forward to furthering our discussion on this matter.

**Comment by camilamacedo86** [comment]
HI @vkhoroz,

Regards: https://github.com/foundriesio/fioctl/pull/271#issuecomment-1733637007

- Considering Golang’s notable stability, is there a reason not to keep all projects updated?
- Could you possibly share an example of this? I haven’t yet come across an instance where Golang’s stability led to a breaking change that wasn’t caught during the build.

**I’m curious to understand in which scenarios a Golang upgrade would introduce issues not identified during the build. Could you provide an example or elaborate a bit more on this?**

**Comment by camilamacedo86** [comment]
HI @vkhoroz,

Regards: https://github.com/foundriesio/fioctl/pull/271#issuecomment-1733637007

- Considering Golang’s notable stability, is there a reason not to keep all projects updated?

**I’m curious to understand in which scenarios a Golang upgrade would introduce issues not identified during the build. Could you provide an example or elaborate a bit more on this?** 

**Regards upgrade dependencies;**
I can think that a dep/lib introduces an issue/regression which could affect a functionality, however, it seems something unlike to be critical and consequently a low risk to take.

**Comment by vkhoroz** [comment]
> I’m curious to understand in which scenarios a Golang upgrade would introduce issues not identified during the build. Could you provide an example or elaborate a bit more on this?

For example this: https://github.com/golang/go/issues/58966

@quaresmajose might still remember the full story. From my experience it was painful.

**Comment by vkhoroz** [comment]
> I can think that a dep/lib introduces an issue/regression which could affect a functionality, however, it seems something unlike to be critical and consequently a low risk to take.

It could be a low risk if we had tests.

But, we have no tests, meaning that we accept upgrade if/when:
- they contain a critical security fix applicable to our usage of a lib.
- they contain a vital functionality we want to leverage.

In any case, we run regression testing for affected functions.

**Pull request closed without merging**
