### PR TITLE
Re-sign production targets when rotating offline targets keys

### PR DESCRIPTION
**Pull request by vkhoroz**

### CODE REVIEW

**Comment by vkhoroz** [comment]
@mike-sul

**Comment by doanac** [comment]
took me a bit to wrap my mind around the `TargetsSignatures`. Looks good, but CI is broke - https://ci.foundries.io/projects/fioctl/builds/150/unit-test/artifacts/console.log

**Comment by doanac** [comment]
looks good. I'm going to review the rest api today and then we can merge. feel free to squash now if you want to have it all ready

**Review by doanac — APPROVED** [review]
Looks good

**Comment by vkhoroz** [comment]
squahed

**Pull request merged**
